import React, { memo } from 'react';
import { formatCurrency } from '../../utils/formatters';
import { FULL_TIME_CONFIG, BOSS_CONFIG } from '../../config/bossConfig';

/**
 * 列印報表元件
 */
const BossPrintReport = memo(({ financial, opsCosts }) => {
    const fmt = formatCurrency;

    return (
        <div className="boss-print-report">
            <div className="boss-print-header">
                <h1>營運配置損益報告書</h1>
                <p>日期: {new Date().toLocaleDateString()}</p>
            </div>

            <div className="boss-print-summary">
                <div className="boss-print-section">
                    <h2>全校財務摘要</h2>
                    <div className="boss-print-rows">
                        <div className="boss-print-row">
                            <span>總預估月營收:</span>
                            <span>${fmt(financial.totalRev)}</span>
                        </div>
                        <div className="boss-print-row">
                            <span>老師總薪資支出:</span>
                            <span>-${fmt(financial.totalSal)}</span>
                        </div>
                        <div className="boss-print-row">
                            <span>固定營運支出:</span>
                            <span>-${fmt(opsCosts.rent + opsCosts.loan + opsCosts.marketing)}</span>
                        </div>
                        <div className="boss-print-row">
                            <span>變動/浮動支出:</span>
                            <span>-${fmt(financial.ptCost + financial.misc + financial.extraRent)}</span>
                        </div>
                        <div className="boss-print-row total">
                            <span>最終月盈餘預估:</span>
                            <span>${fmt(financial.net)}</span>
                        </div>
                    </div>
                </div>

                <div className="boss-print-section">
                    <h2>規模績效指標</h2>
                    <div className="boss-print-rows">
                        <div className="boss-print-row">
                            <span>目前招生總人數:</span>
                            <span>{financial.totalStud} 人</span>
                        </div>
                        <div className="boss-print-row">
                            <span>目標達成率 ({BOSS_CONFIG.GOAL_STUDENTS}人):</span>
                            <span>{financial.progress.toFixed(1)}%</span>
                        </div>
                        <div className="boss-print-row">
                            <span>平均淨利潤率:</span>
                            <span>{financial.margin.toFixed(1)}%</span>
                        </div>
                        <div className="boss-print-row">
                            <span>人均月淨利貢獻:</span>
                            <span>${fmt(financial.totalStud > 0 ? financial.net / financial.totalStud : 0)}</span>
                        </div>
                    </div>
                </div>
            </div>

            <table className="boss-print-table">
                <thead>
                    <tr>
                        <th>師資姓名/類別</th>
                        <th>課程規模明細</th>
                        <th>實際人數</th>
                        <th>預估貢獻</th>
                    </tr>
                </thead>
                <tbody>
                    {financial.teacherData.map(t => (
                        <tr key={t.id}>
                            <td>
                                {t.name} <span className="boss-print-type">({t.teacherType})</span>
                            </td>
                            <td>
                                {t.classList.map(c => (
                                    <div key={c.id}>
                                        • {c.level === 'advanced' ? '[進階]' : '[標準]'} {c.type}人班 ({c.frequency === 'single' ? '單日' : '全期'})
                                    </div>
                                ))}
                            </td>
                            <td className="center">
                                {t.classList.reduce((s, c) => s + c.count, 0)} 人
                            </td>
                            <td className="right">${fmt(t.tProfit)}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <p className="boss-print-footer">
                Management Confidential • operation lab v3.2 • generated by system automated logic
            </p>
        </div>
    );
});

BossPrintReport.displayName = 'BossPrintReport';

export default BossPrintReport;
